### ISSUE TITLE
input files not in Buildconf/mom.input_data_list

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/MOM_interface#114]
I found that file ocean_hgrid_180829.nc is not listed in Buildconf/mom.input_data_list
and therefor will not be automatically downloaded from the inputdata server.

Are there other files like this in MOM?

**Comment by jedwards4b** [comment]
Yes, there is a list of files in MOM_input that should be added to Buildconf/mom.input_data_list

I also noticed that the INPUTDIR variable in that file does not work correctly if DIN_LOC_ROOT ends in a '/'

**Comment by gustavo-marques** [comment]
I think this is already happening in 
https://github.com/ESCOMP/MOM_interface/blob/main/param_templates/input_data_list.yaml

**Comment by jedwards4b** [comment]
Are you saying MOM is using a different mechanism and not check_input_data?   I am working on frontera today and found that I had to download the mom input files by hand.

**Comment by gustavo-marques** [comment]
@alperaltuntas, can you please confirm this?

**Comment by jedwards4b** [comment]
I had another look and see that the files are listed in Buildconf/mom.input_data_list on cheyenne but they are not on listed in that file on frontera.

**Comment by jedwards4b** [comment]
I'm sorry, I just tried a new case on frontera and it seems that the files are listed in mom.input_data_list
Not sure what happened the first time I did this.
