### ISSUE TITLE
mom diag_table inputfiles not in mom.input_data_list

### ISSUE THREAD

**Issue by jedwards4b** [ESCOMP/MOM_interface#116]
This is the list of files in mom.input_data_list
```
cat Buildconf/mom.input_data_list
ocean_hgrid = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/ocean_hgrid_180829.nc
ocean_vgrid1 = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/vgrid_65L_20200626.nc
ocean_topog = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/ocean_topog_200701.nc
tempsalt = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/woa18_04_initial_conditions.nc
saltrestore = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/state_restore_tx0.66v1_20200616.nc
tidal = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/energy_new_t0.66v1_conserve_190315.nc
ocean_channel = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/MOM_channels_global_tx06v1
ocean_seaw = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/seawifs-clim-1997-2010-tx0.66v1.nc
cfcs_forcing = /glade/p/cesmdata/inputdata/ocn/mom/tx0.66v1/CFCs_tx0.66v1_v2_5_210430.nc
```
It does not include DIAG_COORD_DEF_RHO2 = "FILE:ocean_rho2_190917.nc,interfaces=rho2"
which appears in Buildconf/momconf/MOM_input

**Comment by gustavo-marques** [comment]
Yes, we need to include ocean_rho2_190917.nc. Thanks for catching that and letting us know.
MOM_input is generated internally at compile time so I believe it does not need to go in mom.input_data_list. @alperaltuntas can confirm this.

**Comment by jedwards4b** [comment]
@gustavo-marques I believe that it does.  mom.input_data_list is used by cime to determine what files need to be downloaded from the inputdata server, if the file is not listed here it will not be downloaded.

**Comment by alperaltuntas** [comment]
Yes it should be added to mom.input_data_list, i will follow up with a PR once I am able to run an izumi test.
