### ISSUE TITLE
Move grid metrics from ocean_geometry to static output file

### ISSUE THREAD

**Issue by fobryan3** [ESCOMP/MOM_interface#122]
For use with xgcm it would be very convenient to have all of the grid metric information (dxCu, dyCu, etc) that is currently written to ocean_geometry written to the ${CASE}/ocn/hist/${CASE}.mom6.static.nc file for each experiment. ocean_geometry .nc does not seem to be moved by the short-term archiver whereas static.nc is. Some of the output in these two files is currently redundant and outputting the union of the two sets to a single file would be preferable.

**Comment by gustavo-marques** [comment]
We now save ocean_geometry, and that solves the issue raised here.
