### ISSUE TITLE
Rename MOM_mask_table to include PE count?

### ISSUE THREAD

**Issue by mnlevy1981** [ESCOMP/MOM_interface#139]
I had a MOM + MARBL run fail with the message

```
FATAL from PE     0: fms_io(parse_mask_table_2d): layout in file /glade/p/cesmdata/cseg/inputdata/ocn/mom/tx0.66v1/MOM_mask_table does not match size of maskmap for MOM_in
```

It seems that

1. If `MASKTABLE` points to a file that doesn't exist, the model runs without trying to mask out land points
2. If we use a naming convention like `MOM_mask_table_${GRID}_${NTASKS_OCN}_${NTHRDS_OCN}` then we could introduce new masks as we update grids / PE layouts without affecting existing runs

For my development, I simply added `MASKTABLE = "MOM_mask_table2"` to `user_nl_mom` to go back to a non-existent file so it's not clear which of the files in `param_templates/` would need to be updated to make this change

**Comment by alperaltuntas** [comment]
I believe this issue is now irrelevant due to the introduction of auto mask table generation.
