### ISSUE TITLE
Better support of multiple vertical coordinates

### ISSUE THREAD

**Issue by mnlevy1981** [ESCOMP/MOM_interface#152]
I think we should add `MOM6_VERTICAL_COORD` (or something similar) to `env_run.xml` that let's users choose between `zstar` and `hybrid`, and then `ParamGen` and `MOM_input.yaml` can get the parameters right for either. This will make it easier to run experiments comparing the two options.

Note that there might also need to be some work done to support the hybrid coordinate; when I make changes in `user_nl_mom`, I need `ALE_COORDINATE_CONFIG` to specify a file in my run directory. It should support pointing to a file in inputdata rather than requiring a copy into `RUNDIR`.

**Comment by gustavo-marques** [comment]
Solved via https://github.com/ESCOMP/MOM_interface/pull/158
