### ISSUE TITLE
Need to correct history file suffixes for test runs

### ISSUE THREAD

**Issue by alperaltuntas** [ESCOMP/MOM_interface#171]
When `TEST=True`, the diag_table output frequency is set to 1 day, but the file suffix remains `4yr-%2mo`, which means that the history files are constantly overriden at each day, and only including the final day of the run. This should be corrected either by:
 - writing out history files for only the last day of the test runs, OR,
 - writing out history files for all of the days (which is probably an overkill, causing an unnecessary slowdown.)

Thanks to @jedwards4b for noticing this issue.

**Comment by mnlevy1981** [comment]
> writing out history files for all of the days (which is probably an overkill, causing an unnecessary slowdown.)

I think the default option should be only writing output on the last day, but a mechanism to write history files every day would be great for #167
