### ISSUE TITLE
Add a gnu _D test to aux_mom and pr_mom

### ISSUE THREAD

**Issue by alperaltuntas** [ESCOMP/MOM_interface#176]

**Comment by mnlevy1981** [comment]
FYI, I opened https://github.com/iangrooms/stochastic_physics/pull/1 with a fix for the failing test

**Comment by mnlevy1981** [comment]
Updating the external in MOM to https://github.com/iangrooms/stochastic_physics/releases/tag/ocn_skeb_240807 should pass debug tests with gnu
