### ISSUE TITLE
Standalone MOM6 build not working

### ISSUE THREAD

**Issue by alperaltuntas** [ESCOMP/MOM_interface#185]
The `build_examples-ncar.sh` doesn't work on derecho. More info to come...

hash id: dd7a43d

**Comment by manishvenu** [comment]
It looks like the Standalone MOM6 build is working for this commit. Please see [here](https://docs.google.com/document/d/1JnWAwLepNcWi-Rn9SbgxQmX3hnjSAUndZckf4TOBlZs/edit?usp=sharing) for the test output/information.

Thanks,
Manish V.

**Comment by manishvenu** [comment]
FMS Build Error was fixed in https://github.com/ESCOMP/FMS/pull/2
