### ISSUE TITLE
Error trying to checkout External dependencies

### ISSUE THREAD

**Issue by gdicker1** [ESCOMP/MOM_interface#37]
This change has caused some issues for me when trying to follow the guide at: https://github.com/ESCOMP/MOM_interface/wiki/Quick-Start

I clone the new repo
`git clone https://github.com/alperaltuntas/cesm.git cesm2.mom6`
Make sure I'm on the correct branch
`git checkout mom6`
But when I try to get the submodules using:
`./manage_externals/checkout_externals mom cice cime fms cvmix marbl`
I get the error shown below

```Processing externals description file : Externals.cfg  
Checking status of externals: mom, cime, cice, fms, marbl, cvmix,  
Checking out externals: mom,  
Processing externals description file : Externals.cfg  
Checking out externals: mom,  
Processing externals description file : ../Externals_MOM.cfg  
ERROR:root:Invalid input: "pkg/mom6_da_hooks" contains unknown item "from_submodule".
``` 
@mvertens 
Commit #: 831e92ae2c9c622e04a15ae7013e2bc759674d0b

**Comment by gustavo-marques** [comment]
[Quick-start](https://github.com/ESCOMP/MOM_interface/wiki/Quick-Start) has been updated and this issue is now fixed. Thanks for reporting this.
