### ISSUE TITLE
Output file names do not adhere to CESM Conventions

### ISSUE THREAD

**Issue by alperaltuntas** [ESCOMP/MOM_interface#47]
Some of our model output data filenames do not adhere to CESM Model Output Data Filenames:
see: http://www.cesm.ucar.edu/models/cesm2/naming_conventions.html#outputFilenames

For example, we need to change
- ```.sfc.``` to ```.hsf.```
- ```.frc.``` to ```.hfr.```
- ```.visc.``` to ```.hvs.```
- ```.static.``` to ```.ist.```
- etc.

**Comment by klindsay28** [comment]
I'm working on a PR for this...

I think we could replace `.sfc` with `.h.sfc` where `sfc` makes use of the optional `[$string]` component in the filename conventions.

Similarly, `.frc` to `.h.frc`, `.rho2` to `h.rho2`, etc.

This would keep the descriptive strings that are currently in place, and follow the precedence in POP filenames such as `pop.h.nday1.0001-01.nc`, listed at https://www.cesm.ucar.edu/models/cesm2/naming-conventions#exampleStaFilenames

@alperaltuntas or @gustavo-marques, any objections?

**Comment by alperaltuntas** [comment]
No objections.
