### ISSUE TITLE
Add option to compile MOM6 using dynamic_symmetric or dynamic

### ISSUE THREAD

**Issue by gustavo-marques** [ESCOMP/MOM_interface#63]
@alperaltuntas, would it possible to control whether MOM6 is compiled with dynamic_symmetric or dynamic via an xml variable? If so, this would be very useful now since the open boundary code does not work in the dynamic mode.

**Comment by alperaltuntas** [comment]
this is doable. I'll work on adding this soon.

**Comment by gustavo-marques** [comment]
Great, thank you!
