### ISSUE TITLE
_read_MOM_input in changes '=' to ' ' in value of MOM parameter

### ISSUE THREAD

**Issue by klindsay28** [ESCOMP/MOM_interface#93]
If the value of a MOM parameter in MOM_input or user_nl has an '=' character in it, like
```
DIAG_COORD_DEF_Z_NK = "FILE:/glade/scratch/klindsay/newton/IRF_20210909.nc,interfaces=depth_edges"
```
an example of https://mom6.readthedocs.io/en/dev-gfdl/api/generated/pages/Diagnostics.html#diagnostic-vertical-coordinates
`_read_MOM_input` in cime_config/MOM_RPS/FType_MOM_params.py converts the '=' to ' '.
The problem is that the line is split using '=', but the parameter value is joined using ' '.
The following patch fixes the problem

```
--- a/cime_config/MOM_RPS/FType_MOM_params.py
+++ b/cime_config/MOM_RPS/FType_MOM_params.py
@@ -63,7 +63,7 @@ class FType_MOM_params(MOM_RPS):
                             if ("=" in line_j):
                                 line_ss     = line_j.split("=")
                                 param_str   = (line_ss[0]).strip()  # the first element is the parameter name
-                                val_str     = ' '.join(line_ss[1:]) # the rest is tha value string
+                                val_str     = '='.join(line_ss[1:]) # the rest is the value string
                                 if '!' in val_str:
                                     val_str = val_str.split("!")[0] # discard the comment in val str, if there is
```

**Comment by alperaltuntas** [comment]
Agreed. But, I think, we need a regex-based implementation here for robustness (that replaces the whole if-block). Will look into it.

**Comment by mnlevy1981** [comment]
Any progress on this? @klindsay28 shared some `user_nl_mom` mods that include setting `DIAG_COORD_DEF_*`, so I ran into this same issue. I'm using the workaround mentioned in the initial report, but I won't commit it to my branch

**Comment by alperaltuntas** [comment]
Just submitted a PR that fixes this.
